ルーティングの追加とその他不具合修正
nkc-ug/yagi5108 pull request #63
Opened 2023-08-01 13:12 UTC by MinamizonoEno

・routesフォルダにRoutersファイル追加
・componentsフォルダにpagesフォルダとpartsフォルダ追加、それに伴いApp,main.tsx以外のファイル整理
・食事回数を３回に減らしたことで進化時のポップアップが表示されなくなっていたのを修正
・進化ポップアップのうしろで進化前進化後のヤギが同時に存在するバグの修正

2023-08-01 13:44 UTC, Yuma-Satake requested changes
成長回数のやつは毎回変更しそうだから、あそこだけなおしとこう👌
そこ以外はルーティングよくできてたナイス！

2023-08-01 13:44 UTC, Yuma-Satake commented on src/components/parts/Branch.ts
> +    if (emotionData[emotion as keyof emotionDataType] > max && index < 4) {
授業でやったかもしれんけど、いわゆるマジックナンバーだから、どっかに定数定義して置いとくのがいいと思う。
定数にしといて、それをインポートして使う感じで

2023-08-10 03:03 UTC, MinamizonoEno commented
- READ.mdに各種説明の追加とcompisition.mdへのリンクの追加
- composition.mdにディレクトリ構成のツリーとディレクトリの説明の追加

2023-08-10 03:13 UTC, Yuma-Satake requested changes
ナイスmd👏
じゃないところが修正だから頑張れ🤝

2023-08-10 03:13 UTC, Yuma-Satake commented on doc/composition.md
> +
しっかりツリー表示されててえらい👏

2023-08-10 03:13 UTC, Yuma-Satake commented on src/components/EvolutionPopup.tsx
> +          {props.eatCount >= 4 ? (
`eatLimit`君、使われてなくない？泣いちゃう

2023-08-10 03:13 UTC, Yuma-Satake commented on src/types/EatLimit.ts
置き場所は `src/const/eatLimit.ts`（tsxファイルじゃない&型ファイルじゃないから、小文字スタート）かな

2023-08-10 03:13 UTC, Yuma-Satake commented on src/types/EatLimit.ts
> +export const eatLimit = 3;
定数は全部大文字にしたい気持ち
`EATLIMIT`

2023-08-11 14:48 UTC, Yuma-Satake approved these changes
お疲れ！！
ナイスルーティング・Doc👏

2023-08-12 00:13 UTC, merged